services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-net
    restart: unless-stopped

  the-internet:
    image: gprestes/the-internet
    container_name: the-internet
    ports:
      - "7080:5000"
    networks:
      - ci-net
    restart: unless-stopped

networks:
  ci-net: