version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-cypress
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    # Adding docker to the container:
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y docker.io &&
        /usr/local/bin/jenkins.sh
      "

volumes:
  jenkins_home:
