name: Cypress Automation Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Pull Docker image of the app
        run: docker pull gprestes/the-internet

      - name: Start the app container
        run: docker run -d -p 7080:5000 gprestes/the-internet

      - name: Wait for the app to be ready
        run: npx wait-on http://localhost:7080

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Cypress videos (on failure)
        if: failure()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: cypress-screenshots
          path: cypress/screenshots